Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
#import pyodbc
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy import text


#server = 'DESKTOP-BQEVUFH\SQLEXPRESS'
#database = 'prosaindata'
#username = 'DESKTOP-BQEVUFH\Ikhtiar'
#password = ''

DRIVER = "ODBC Driver 17 for SQL Server"
USERNAME = "sa"
PSSWD = "123455"
SERVERNAME = "DESKTOP-BQEVUFH"
INSTANCENAME = "\SQLEXPRESS"
DB = "prosaindata"
TABLE = "dbo.prosain"



mysqlEngine = create_engine('mysql+mysqlconnector://root:@localhost:3306/prosaindata')
pgEngine = create_engine('postgresql://postgres:root@localhost/prosain')
#sqlServerEngine = create_engine('mssql+pyodbc://DESKTOP-BQEVUFH\Ikhtiar:@DESKTOP-BQEVUFH\SQLEXPRESS/prosaindata?driver=ODBC+Driver+17+for+SQL+Server')
ElephantEngine = create_engine('postgresql://nvbxxywe:30dMEzpIkS1wsWpnH3vvfPFHXlcThP0n@floppy.db.elephantsql.com/nvbxxywe')
#sqlServerEngine = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
sqlServerEngine = sqlalchemy.create_engine(
    f"mssql+pyodbc://{USERNAME}:{PSSWD}@{SERVERNAME}{INSTANCENAME}/{DB}?driver={DRIVER}", fast_executemany=True)
# query untuk mengambil data dari tabel
# mysqlQuery = text("SELECT id, petallength FROM iris")
ElephantServerQuery = text("SELECT sepalwidth FROM prosaindata")
mysqlQuery = text("SELECT petallength FROM prosaindata")
pgQuery = text("SELECT sepallength FROM prosaindata")
sqlServerQuery = text("SELECT petalwidth, class FROM dbo.prosain")

# membaca data dari database ke dalam DataFrame
with mysqlEngine.connect() as mysqlConn:
    mysqlDf = pd.read_sql(mysqlQuery, mysqlConn)

with pgEngine.connect() as pgConn:
    pgDf = pd.read_sql(pgQuery, pgConn)
    
with sqlServerEngine.connect() as sqlServerConn:
    sqlServerDf = pd.read_sql(sqlServerQuery, sqlServerConn)

with ElephantEngine.connect() as ElephantServerConn:
    ElephantServerDf = pd.read_sql(ElephantServerQuery, ElephantServerConn)
    
# menampilkan lima baris pertama dari DataFrame
# print(pgDf.head())
# print(mysqlDf.head())
# print(sqlServerDf.head())


# # concate dataFrame (Cara 1)
new_df = pd.concat([mysqlDf, pgDf, ElephantServerDf, sqlServerDf], axis=1)
new_df.head()

# # merge dataFrame (Cara 2)
# merged_df = pd.merge(pgDf, mysqlDf, on='id')
# merged_df.head()
------------------


[0;31m[0m
[0;31mMySQLInterfaceError[0mTraceback (most recent call last)
[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py[0m in [0;36m_open_connection[0;34m(self)[0m
[1;32m    290[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 291[0;31m             [0mself[0m[0;34m.[0m[0m_cmysql[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m**[0m[0mcnx_kwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    292[0m             [0mself[0m[0;34m.[0m[0m_cmysql[0m[0;34m.[0m[0mconverter_str_fallback[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_converter_str_fallback[0m[0;34m[0m[0;34m[0m[0m

[0;31mMySQLInterfaceError[0m: Can't connect to MySQL server on 'localhost:3306' (99)

The above exception was the direct cause of the following exception:

[0;31mDatabaseError[0mTraceback (most recent call last)
[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py[0m in [0;36m__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    144[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 145[0;31m                 [0mself[0m[0;34m.[0m[0m_dbapi_connection[0m [0;34m=[0m [0mengine[0m[0;34m.[0m[0mraw_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    146[0m             [0;32mexcept[0m [0mdialect[0m[0;34m.[0m[0mloaded_dbapi[0m[0;34m.[0m[0mError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py[0m in [0;36mraw_connection[0;34m(self)[0m
[1;32m   3287[0m         """
[0;32m-> 3288[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mpool[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3289[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36mconnect[0;34m(self)[0m
[1;32m    451[0m         """
[0;32m--> 452[0;31m         [0;32mreturn[0m [0m_ConnectionFairy[0m[0;34m.[0m[0m_checkout[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    453[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m_checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1267[0m         [0;32mif[0m [0;32mnot[0m [0mfairy[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1268[0;31m             [0mfairy[0m [0;34m=[0m [0m_ConnectionRecord[0m[0;34m.[0m[0mcheckout[0m[0;34m([0m[0mpool[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1269[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36mcheckout[0;34m(cls, pool)[0m
[1;32m    715[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 716[0;31m             [0mrec[0m [0;34m=[0m [0mpool[0m[0;34m.[0m[0m_do_get[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    717[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py[0m in [0;36m_do_get[0;34m(self)[0m
[1;32m    167[0m             [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 168[0;31m                 [0;32mwith[0m [0mutil[0m[0;34m.[0m[0msafe_reraise[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    169[0m                     [0mself[0m[0;34m.[0m[0m_dec_overflow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py[0m in [0;36m__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    146[0m             [0mself[0m[0;34m.[0m[0m_exc_info[0m [0;34m=[0m [0;32mNone[0m  [0;31m# remove potential circular references[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 147[0;31m             [0;32mraise[0m [0mexc_value[0m[0;34m.[0m[0mwith_traceback[0m[0;34m([0m[0mexc_tb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    148[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py[0m in [0;36m_do_get[0;34m(self)[0m
[1;32m    165[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 166[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_create_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    167[0m             [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m_create_connection[0;34m(self)[0m
[1;32m    392[0m [0;34m[0m[0m
[0;32m--> 393[0;31m         [0;32mreturn[0m [0m_ConnectionRecord[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    394[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m__init__[0;34m(self, pool, connect)[0m
[1;32m    677[0m         [0;32mif[0m [0mconnect[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 678[0;31m             [0mself[0m[0;34m.[0m[0m__connect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    679[0m         [0mself[0m[0;34m.[0m[0mfinalize_callback[0m [0;34m=[0m [0mdeque[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m__connect[0;34m(self)[0m
[1;32m    901[0m         [0;32mexcept[0m [0mBaseException[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 902[0;31m             [0;32mwith[0m [0mutil[0m[0;34m.[0m[0msafe_reraise[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    903[0m                 [0mpool[0m[0;34m.[0m[0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Error on connect(): %s"[0m[0;34m,[0m [0me[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py[0m in [0;36m__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    146[0m             [0mself[0m[0;34m.[0m[0m_exc_info[0m [0;34m=[0m [0;32mNone[0m  [0;31m# remove potential circular references[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 147[0;31m             [0;32mraise[0m [0mexc_value[0m[0;34m.[0m[0mwith_traceback[0m[0;34m([0m[0mexc_tb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    148[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m__connect[0;34m(self)[0m
[1;32m    897[0m             [0mself[0m[0;34m.[0m[0mstarttime[0m [0;34m=[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 898[0;31m             [0mself[0m[0;34m.[0m[0mdbapi_connection[0m [0;34m=[0m [0mconnection[0m [0;34m=[0m [0mpool[0m[0;34m.[0m[0m_invoke_creator[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    899[0m             [0mpool[0m[0;34m.[0m[0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Created new connection %r"[0m[0;34m,[0m [0mconnection[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py[0m in [0;36mconnect[0;34m(connection_record)[0m
[1;32m    636[0m [0;34m[0m[0m
[0;32m--> 637[0;31m             [0;32mreturn[0m [0mdialect[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m*[0m[0mcargs[0m[0;34m,[0m [0;34m**[0m[0mcparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    638[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py[0m in [0;36mconnect[0;34m(self, *cargs, **cparams)[0m
[1;32m    613[0m         [0;31m# inherits the docstring from interfaces.Dialect.connect[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 614[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mloaded_dbapi[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m*[0m[0mcargs[0m[0;34m,[0m [0;34m**[0m[0mcparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    615[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py[0m in [0;36mconnect[0;34m(*args, **kwargs)[0m
[1;32m    292[0m     [0;32mif[0m [0mCMySQLConnection[0m [0;32mand[0m [0;32mnot[0m [0muse_pure[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 293[0;31m         [0;32mreturn[0m [0mCMySQLConnection[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    294[0m     [0;32mreturn[0m [0mMySQLConnection[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py[0m in [0;36m__init__[0;34m(self, **kwargs)[0m
[1;32m    119[0m         [0;32mif[0m [0mkwargs[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 120[0;31m             [0mself[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    121[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py[0m in [0;36mconnect[0;34m(self, **kwargs)[0m
[1;32m   1180[0m         [0mself[0m[0;34m.[0m[0mdisconnect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1181[0;31m         [0mself[0m[0;34m.[0m[0m_open_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1182[0m         [0;31m# Server does not allow to run any other statement different from ALTER[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py[0m in [0;36m_open_connection[0;34m(self)[0m
[1;32m    295[0m         [0;32mexcept[0m [0mMySQLInterfaceError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 296[0;31m             raise get_mysql_exception(
[0m[1;32m    297[0m                 [0mmsg[0m[0;34m=[0m[0merr[0m[0;34m.[0m[0mmsg[0m[0;34m,[0m [0merrno[0m[0;34m=[0m[0merr[0m[0;34m.[0m[0merrno[0m[0;34m,[0m [0msqlstate[0m[0;34m=[0m[0merr[0m[0;34m.[0m[0msqlstate[0m[0;34m[0m[0;34m[0m[0m

[0;31mDatabaseError[0m: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (99)

The above exception was the direct cause of the following exception:

[0;31mDatabaseError[0mTraceback (most recent call last)
[0;32m<ipython-input-6-88a01e37c49d>[0m in [0;36m<cell line: 38>[0;34m()[0m
[1;32m     36[0m [0;34m[0m[0m
[1;32m     37[0m [0;31m# membaca data dari database ke dalam DataFrame[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 38[0;31m [0;32mwith[0m [0mmysqlEngine[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m)[0m [0;32mas[0m [0mmysqlConn[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     39[0m     [0mmysqlDf[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_sql[0m[0;34m([0m[0mmysqlQuery[0m[0;34m,[0m [0mmysqlConn[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     40[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py[0m in [0;36mconnect[0;34m(self)[0m
[1;32m   3262[0m         """
[1;32m   3263[0m [0;34m[0m[0m
[0;32m-> 3264[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_connection_cls[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3265[0m [0;34m[0m[0m
[1;32m   3266[0m     [0;32mdef[0m [0mraw_connection[0m[0;34m([0m[0mself[0m[0;34m)[0m [0;34m->[0m [0mPoolProxiedConnection[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py[0m in [0;36m__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    145[0m                 [0mself[0m[0;34m.[0m[0m_dbapi_connection[0m [0;34m=[0m [0mengine[0m[0;34m.[0m[0mraw_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    146[0m             [0;32mexcept[0m [0mdialect[0m[0;34m.[0m[0mloaded_dbapi[0m[0;34m.[0m[0mError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 147[0;31m                 Connection._handle_dbapi_exception_noconnection(
[0m[1;32m    148[0m                     [0merr[0m[0;34m,[0m [0mdialect[0m[0;34m,[0m [0mengine[0m[0;34m[0m[0;34m[0m[0m
[1;32m    149[0m                 )

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py[0m in [0;36m_handle_dbapi_exception_noconnection[0;34m(cls, e, dialect, engine, is_disconnect, invalidate_pool_on_disconnect, is_pre_ping)[0m
[1;32m   2424[0m         [0;32melif[0m [0mshould_wrap[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2425[0m             [0;32massert[0m [0msqlalchemy_exception[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2426[0;31m             [0;32mraise[0m [0msqlalchemy_exception[0m[0;34m.[0m[0mwith_traceback[0m[0;34m([0m[0mexc_info[0m[0;34m[[0m[0;36m2[0m[0;34m][0m[0;34m)[0m [0;32mfrom[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2427[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2428[0m             [0;32massert[0m [0mexc_info[0m[0;34m[[0m[0;36m1[0m[0;34m][0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py[0m in [0;36m__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    143[0m         [0;32mif[0m [0mconnection[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    144[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 145[0;31m                 [0mself[0m[0;34m.[0m[0m_dbapi_connection[0m [0;34m=[0m [0mengine[0m[0;34m.[0m[0mraw_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    146[0m             [0;32mexcept[0m [0mdialect[0m[0;34m.[0m[0mloaded_dbapi[0m[0;34m.[0m[0mError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    147[0m                 Connection._handle_dbapi_exception_noconnection(

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py[0m in [0;36mraw_connection[0;34m(self)[0m
[1;32m   3286[0m [0;34m[0m[0m
[1;32m   3287[0m         """
[0;32m-> 3288[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mpool[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3289[0m [0;34m[0m[0m
[1;32m   3290[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36mconnect[0;34m(self)[0m
[1;32m    450[0m [0;34m[0m[0m
[1;32m    451[0m         """
[0;32m--> 452[0;31m         [0;32mreturn[0m [0m_ConnectionFairy[0m[0;34m.[0m[0m_checkout[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    453[0m [0;34m[0m[0m
[1;32m    454[0m     [0;32mdef[0m [0m_return_conn[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mrecord[0m[0;34m:[0m [0mConnectionPoolEntry[0m[0;34m)[0m [0;34m->[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m_checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1266[0m [0;34m[0m[0m
[1;32m   1267[0m         [0;32mif[0m [0;32mnot[0m [0mfairy[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1268[0;31m             [0mfairy[0m [0;34m=[0m [0m_ConnectionRecord[0m[0;34m.[0m[0mcheckout[0m[0;34m([0m[0mpool[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1269[0m [0;34m[0m[0m
[1;32m   1270[0m             [0;32mif[0m [0mthreadconns[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36mcheckout[0;34m(cls, pool)[0m
[1;32m    714[0m             [0mrec[0m [0;34m=[0m [0mcast[0m[0;34m([0m[0m_ConnectionRecord[0m[0;34m,[0m [0mpool[0m[0;34m.[0m[0m_do_get[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    715[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 716[0;31m             [0mrec[0m [0;34m=[0m [0mpool[0m[0;34m.[0m[0m_do_get[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    717[0m [0;34m[0m[0m
[1;32m    718[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py[0m in [0;36m_do_get[0;34m(self)[0m
[1;32m    166[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_create_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    167[0m             [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 168[0;31m                 [0;32mwith[0m [0mutil[0m[0;34m.[0m[0msafe_reraise[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    169[0m                     [0mself[0m[0;34m.[0m[0m_dec_overflow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    170[0m                 [0;32mraise[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py[0m in [0;36m__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m             [0;32massert[0m [0mexc_value[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m    146[0m             [0mself[0m[0;34m.[0m[0m_exc_info[0m [0;34m=[0m [0;32mNone[0m  [0;31m# remove potential circular references[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 147[0;31m             [0;32mraise[0m [0mexc_value[0m[0;34m.[0m[0mwith_traceback[0m[0;34m([0m[0mexc_tb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    148[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    149[0m             [0mself[0m[0;34m.[0m[0m_exc_info[0m [0;34m=[0m [0;32mNone[0m  [0;31m# remove potential circular references[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/impl.py[0m in [0;36m_do_get[0;34m(self)[0m
[1;32m    164[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0m_inc_overflow[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    165[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 166[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_create_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    167[0m             [0;32mexcept[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    168[0m                 [0;32mwith[0m [0mutil[0m[0;34m.[0m[0msafe_reraise[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m_create_connection[0;34m(self)[0m
[1;32m    391[0m         [0;34m"""Called by subclasses to create a new ConnectionRecord."""[0m[0;34m[0m[0;34m[0m[0m
[1;32m    392[0m [0;34m[0m[0m
[0;32m--> 393[0;31m         [0;32mreturn[0m [0m_ConnectionRecord[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    394[0m [0;34m[0m[0m
[1;32m    395[0m     def _invalidate(

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m__init__[0;34m(self, pool, connect)[0m
[1;32m    676[0m         [0mself[0m[0;34m.[0m[0m__pool[0m [0;34m=[0m [0mpool[0m[0;34m[0m[0;34m[0m[0m
[1;32m    677[0m         [0;32mif[0m [0mconnect[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 678[0;31m             [0mself[0m[0;34m.[0m[0m__connect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    679[0m         [0mself[0m[0;34m.[0m[0mfinalize_callback[0m [0;34m=[0m [0mdeque[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    680[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m__connect[0;34m(self)[0m
[1;32m    900[0m             [0mself[0m[0;34m.[0m[0mfresh[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    901[0m         [0;32mexcept[0m [0mBaseException[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 902[0;31m             [0;32mwith[0m [0mutil[0m[0;34m.[0m[0msafe_reraise[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    903[0m                 [0mpool[0m[0;34m.[0m[0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Error on connect(): %s"[0m[0;34m,[0m [0me[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    904[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py[0m in [0;36m__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m             [0;32massert[0m [0mexc_value[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m    146[0m             [0mself[0m[0;34m.[0m[0m_exc_info[0m [0;34m=[0m [0;32mNone[0m  [0;31m# remove potential circular references[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 147[0;31m             [0;32mraise[0m [0mexc_value[0m[0;34m.[0m[0mwith_traceback[0m[0;34m([0m[0mexc_tb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    148[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    149[0m             [0mself[0m[0;34m.[0m[0m_exc_info[0m [0;34m=[0m [0;32mNone[0m  [0;31m# remove potential circular references[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/pool/base.py[0m in [0;36m__connect[0;34m(self)[0m
[1;32m    896[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    897[0m             [0mself[0m[0;34m.[0m[0mstarttime[0m [0;34m=[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 898[0;31m             [0mself[0m[0;34m.[0m[0mdbapi_connection[0m [0;34m=[0m [0mconnection[0m [0;34m=[0m [0mpool[0m[0;34m.[0m[0m_invoke_creator[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    899[0m             [0mpool[0m[0;34m.[0m[0mlogger[0m[0;34m.[0m[0mdebug[0m[0;34m([0m[0;34m"Created new connection %r"[0m[0;34m,[0m [0mconnection[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    900[0m             [0mself[0m[0;34m.[0m[0mfresh[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/create.py[0m in [0;36mconnect[0;34m(connection_record)[0m
[1;32m    635[0m                         [0;32mreturn[0m [0mconnection[0m[0;34m[0m[0;34m[0m[0m
[1;32m    636[0m [0;34m[0m[0m
[0;32m--> 637[0;31m             [0;32mreturn[0m [0mdialect[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m*[0m[0mcargs[0m[0;34m,[0m [0;34m**[0m[0mcparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    638[0m [0;34m[0m[0m
[1;32m    639[0m         [0mcreator[0m [0;34m=[0m [0mpop_kwarg[0m[0;34m([0m[0;34m"creator"[0m[0;34m,[0m [0mconnect[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py[0m in [0;36mconnect[0;34m(self, *cargs, **cparams)[0m
[1;32m    612[0m     [0;32mdef[0m [0mconnect[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0mcargs[0m[0;34m,[0m [0;34m**[0m[0mcparams[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    613[0m         [0;31m# inherits the docstring from interfaces.Dialect.connect[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 614[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mloaded_dbapi[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m*[0m[0mcargs[0m[0;34m,[0m [0;34m**[0m[0mcparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    615[0m [0;34m[0m[0m
[1;32m    616[0m     [0;32mdef[0m [0mcreate_connect_args[0m[0;34m([0m[0mself[0m[0;34m,[0m [0murl[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py[0m in [0;36mconnect[0;34m(*args, **kwargs)[0m
[1;32m    291[0m [0;34m[0m[0m
[1;32m    292[0m     [0;32mif[0m [0mCMySQLConnection[0m [0;32mand[0m [0;32mnot[0m [0muse_pure[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 293[0;31m         [0;32mreturn[0m [0mCMySQLConnection[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    294[0m     [0;32mreturn[0m [0mMySQLConnection[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    295[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py[0m in [0;36m__init__[0;34m(self, **kwargs)[0m
[1;32m    118[0m [0;34m[0m[0m
[1;32m    119[0m         [0;32mif[0m [0mkwargs[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 120[0;31m             [0mself[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    121[0m [0;34m[0m[0m
[1;32m    122[0m     [0;32mdef[0m [0m_add_default_conn_attrs[0m[0;34m([0m[0mself[0m[0;34m)[0m [0;34m->[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py[0m in [0;36mconnect[0;34m(self, **kwargs)[0m
[1;32m   1179[0m [0;34m[0m[0m
[1;32m   1180[0m         [0mself[0m[0;34m.[0m[0mdisconnect[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1181[0;31m         [0mself[0m[0;34m.[0m[0m_open_connection[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1182[0m         [0;31m# Server does not allow to run any other statement different from ALTER[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1183[0m         [0;31m# when user's password has been expired.[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py[0m in [0;36m_open_connection[0;34m(self)[0m
[1;32m    294[0m                 [0mself[0m[0;34m.[0m[0mconverter[0m[0;34m.[0m[0mstr_fallback[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_converter_str_fallback[0m[0;34m[0m[0;34m[0m[0m
[1;32m    295[0m         [0;32mexcept[0m [0mMySQLInterfaceError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 296[0;31m             raise get_mysql_exception(
[0m[1;32m    297[0m                 [0mmsg[0m[0;34m=[0m[0merr[0m[0;34m.[0m[0mmsg[0m[0;34m,[0m [0merrno[0m[0;34m=[0m[0merr[0m[0;34m.[0m[0merrno[0m[0;34m,[0m [0msqlstate[0m[0;34m=[0m[0merr[0m[0;34m.[0m[0msqlstate[0m[0;34m[0m[0;34m[0m[0m
[1;32m    298[0m             ) from err

[0;31mDatabaseError[0m: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (99)
(Background on this error at: https://sqlalche.me/e/20/4xp6)

